#!/bin/bash
echo 'lol'
createuser ${DATABASE_USER}
createdb ${DATABASE_NAME}

psql -c "ALTER USER ${DATABASE_USER} WITH PASSWORD '${DATABASE_PASSWORD}'; GRANT ALL PRIVILEGES ON DATABASE ${DATABASE_NAME} TO ${DATABASE_USER}; "
