# Generated by Django 3.0.3 on 2020-02-25 00:35

import Pizzeria_Management.apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200225_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('HM', 'Home'), ('WRK', 'Work'), ('OTHER', 'Other')], default='HOME', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=10, null=True, validators=[Pizzeria_Management.apps.accounts.models.validate_postal_code]),
        ),
    ]
